# Generated by Django 5.0.4 on 2024-05-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chezsb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='assets/img/', upload_to='products/'),
        ),
    ]
